# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGuOpeBIdxWaldBYhhnSCSt4DpnrX1nP
"""

import pandas as pd
import numpy as np

df = pd.read_csv("roaddistance.csv")
df = df.drop(['Road Distance of  Major  Cities'], axis = 1)
df = df.drop(['Unnamed: 22'], axis = 1)
df.head()

arr = df.to_numpy()
arr

df2 = pd.DataFrame(columns = ['First City','Second City','Distance'])
count = 0
for i in range(1, len(arr)):
  city1 = arr[i][0]
  for j in range(1, len(arr[0])):
    city2 = arr[0][j]
    distance = str(arr[i][j])
    if distance=='-':
      distance = '0'
    fact = "edge ('"+city1+"','"+city2+"',"+distance+")."
    dic = {'First City': city1, 'Second City': city2, 'Distance': distance}
    df2 = df2.append(dic, ignore_index = True)
    print(fact,end = ' ')
  count+=1
  print()
print(count)

df2.to_csv('Edge_values.csv', index = False)