# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOTw82Ilmu5lX1861F-AsFxwc6t7G2gs
"""

import geopy

import pandas as pd
import numpy as np

import math

df = pd.read_csv('roaddistance.csv')

df = df.drop(['Road Distance of  Major  Cities'], axis = 1)
df = df.drop(['Unnamed: 22'], axis = 1)

arr = df.to_numpy()
s = set()
for i in range(1, len(arr)):
  city = arr[i][0]
  s.add(city)
for i in range(1, len(arr[0])):
  city = arr[0][i]
  s.add(city)


# fetch all city names
city_names = list(s)
city_names, len(city_names)

from geopy.geocoders import Nominatim



### use geopy library to get the heuristic values between cities
geolocator = Nominatim(user_agent="MyApp")

location = geolocator.geocode("Hyderabad")

print("The latitude of the location is: ", location.latitude)
print("The longitude of the location is: ", location.longitude)

List_geo_cities = []
new_df = pd.DataFrame()
for city1 in city_names:
  location1 = geolocator.geocode(city1)
  latit1 = location1.latitude
  longit1 = location1.longitude

  for city2 in city_names:
    location2 = geolocator.geocode(city2)
    latit2 = location2.latitude
    longit2 = location2.longitude

    dist = math.sqrt((longit2 - longit1)**2 + (latit2 - latit1)**2)
    dic = {'n':city1, 'destination':city2, 'distance':dist}
    new_df = new_df.append(dic, ignore_index = True)
    print(dic)


### the final heuristics are saved in My_Heuristics.csv file
new_df.to_csv('My_Heuristics.csv', index = False)